apiVersion: apps/v1
kind: Job
metadata:
  name: model-job
spec:
  template:
    spec:
      containers:
      - name: model
        image: quay.io/gaalves/playlists-recommender-model:0.1
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
        command: ["python", "./app/app.py"]
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: project2-pvc-gabrielreis
    backoffLimit: 4