apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gabrielreis-model
  template:
    metadata:
      labels:
        app: gabrielreis-model
    spec:
      containers:
      - name: model
        image: quay.io/gaalves/playlists-recommender-model:0.1
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: project2-pvc-gabrielreis