apiVersion: batch/v1
kind: Job
metadata:
  name: model-job-v2
  namespace: gabrielreis
spec:
  template:
    metadata:
      labels:
        app: gabrielreis-model
    spec:
      containers:
      - name: model
        image: quay.io/gaalves/playlists-recommender-model:0.4
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
        env:
        - name: DATASET
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: project2-pv2-gabrielreis
      restartPolicy: Never
  backoffLimit: 4
