apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: gabrielreis-playlist-recommender
    spec:
      containers:
      - name: model
        image: quay.io/gaalves/playlists-recommender-model:0.1