apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment-v2
  namespace: gabrielreis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gabrielreis-model
  template:
    metadata:
      labels:
        app: gabrielreis-model
    spec:
      containers:
      - name: model
        image: quay.io/gaalves/playlists-recommender-model:0.3
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
        env:
        - name: DATASET
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: project2-pv2-gabrielreis