apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gabrielreis
  name: project2-pvc-gabrielreis
spec:
 selector:
    matchLabels:
      namespace: gabrielreis
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi