apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gabrielreis-playlist-recommender
  template:
    metadata:
      labels:
        app: gabrielreis-playlist-recommender
    spec:
      containers:
      - name: server
        image: quay.io/gaalves/playlists-recommender-server:0.1
        ports:
        - containerPort: 52023
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
          readOnly: true
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: project2-pvc-gabrielreis
